postgres:
  container_name: db
  image: postgres
  restart: always
  volumes:
  # Location to save Postgres Database
    - <location>:/data
  environment:
    - PGDATA=/data
    - POSTGRES_PASSWORD-netdisco
    - POSTGRES_USER=netdisco

netdisco:
  container_name: netdisco
  image: sheeprine/docker-netdisco
  restart: always
  ports:
    - 5000:5000
  environment:
    - NETDISCO_DB_USER=netdisco
    - NETDISCO_DB_PASS=netdisco
    - NETDISCO_DOMAIN=domain.local
    - NETDISCO_RO_COMMUNITY=public
    - NETDISCO_WR_COMMUNITY=private
    - NETDISCO_HOME=/netdisco
  volumes:
  # Location to save Config File for Netdisco
    - <location>/deployment.yml:/netdisco/environments/deployment.yml
  links:
    - postgres:db
